language: android
dist: trusty
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

    - build-tools-29.0.2
    - android-28

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    - sys-img-x86-android-26

before_install:
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew --debug assembleDebug
