language: android
dist: trusty
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools

    - build-tools-29.0.2
    - android-28

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

before_install:
  - yes | sdkmanager "platforms;android-28"

script:
  - ./gradlew test
  - ./gradlew assembleDebug

deploy:
  provider: releases
  api-key: $GITHUB_API_KEY
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  name: dev-build-$TRAVIS_TAG
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true
    branch: master

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
